config/routes.rb
Rails.application.routes.draw do
	root 'gossips#index'
  resources :gossips do
  	resources :comments
    resources :likes, only:[:create, :destroy]
  end
  resources :authors
  resources :cities
  resources :sessions, only:[:new,:create,:destroy]

  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'
  get '/welcome/:first_name', to: 'dynamic_pages#welcome', as: 'welcome'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	validates :name, presence: true
	validates :zip_code, 
		presence: true,
		uniqueness: true,
		format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "please enter a valid french zip code" }

	has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
	validates :content, presence: true

	belongs_to :gossip
	belongs_to :user
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	validates :title, 
		presence: true,
		length: {minimum: 3, maximum: 14}
	validates :content, presence: true
	
	belongs_to :user
	has_many :tag_gossip_joins
	has_many :tags, through: :tag_gossip_joins
	has_many :comments
	has_many :likes
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	validates :content, presence: true

	belongs_to :sender, class_name: "User"
	belongs_to :recipient, class_name: "User"	
end

app/models/tag.rb
class Tag < ApplicationRecord
	validates :title, 
		presence: true, 
		uniqueness: true

	has_many :tag_gossip_joins
	has_many :gossips, through: :tag_gossip_joins
end

app/models/tag_gossip_join.rb
class TagGossipJoin < ApplicationRecord
	belongs_to :tag 
	belongs_to :gossip 
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :email,
		presence: true,
		uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
    validates :city, presence: true
    validates :password, length: { minimum: 6 }, on: :create

	belongs_to :city
	has_many :gossips
	has_many :sent_messages, foreign_key: "sender_id", class_name: "PrivateMessage"
	has_many :received_messages, foreign_key: "recipient_id", class_name: "PrivateMessage"
	has_many :comments
	has_many :likes
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
	def new
		@cities = []
		City.all.each do |city|
			@cities << [city.name, city.id]
		end
	end

	def create
		@user = User.new(first_name: params[:first_name], last_name: params[:last_name], description: params[:description], email: params[:email], age: params[:age], city_id: params[:city_id], password: params[:password])
    if @user.save
    	log_in(@user)
      redirect_to root_path, success: "User successfully created !"
    else
      redirect_to new_author_path, danger: "#{@user.errors.full_messages.join(". ")}"
    end
	end

  def show
  	@author = User.find(params[:id])
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
  	@city = City.find(params[:id])
  	@users = User.where(city: params[:id])
  	@gossips = Gossip.where(user: @users.ids)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :authenticate_user, only: [:edit, :new, :create, :show]
	
	def new
	end

	def create
		@comment = Comment.create(content: params[:content], user: current_user, gossip: Gossip.find(params[:gossip_id]))
      	redirect_to gossip_path(params[:gossip_id]), success: "Comment successfully created !"
	end

	def edit
		 @comment = Comment.find(params[:id])
	end

	def update
		@comment = Comment.find(params[:id])
		@comment.update(content: params[:content])
    	redirect_to gossip_path(params[:gossip_id]), success: "Comment successfully edited !"
	end

	def destroy
		@comment = Comment.find(params[:id])
	    @comment.destroy
	    redirect_to gossip_path(params[:gossip_id]), success: "Comment successfully deleted !"
	end

	private

  def authenticate_user
    unless current_user
      redirect_to new_session_path, danger: "Hmmmm, seems like you are not logged in 🤔"
    end
  end

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  before_action :authenticate_user, only: [:edit, :new, :create, :show]

  def index
    @gossips = Gossip.all
  end

  def new
  end

  def create
    @gossip = Gossip.new(title: params[:title], content: params[:content], user: current_user)

    if @gossip.save
      redirect_to root_path, success: "Gossip successfully created !"
    else
      redirect_to new_gossip_path, danger: "#{@gossip.errors.full_messages.join(". ")}"
    end
  end

  def show
    @gossip = Gossip.find(params[:id])
    @comments = Comment.where(gossip: params[:id])
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
  if @gossip.update(title: params[:title], content: params[:content])
    redirect_to gossip_path(params[:id]), success: "Gossip successfully edited !"
  else
    redirect_to edit_gossip_path(params[:id]), danger: "#{@gossip.errors.full_messages.join(". ")}"
    end  
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to root_path, success: "Gossip successfully deleted !"
  end

  private

  def authenticate_user
    unless current_user
      redirect_to new_session_path, danger: "Hmmmm, seems like you are not logged in 🤔"
    end
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

	before_action :authenticate_user, only: [:create, :destroy]

	def create
		Like.create(user: current_user, gossip: Gossip.find(params[:gossip_id]))
		redirect_back fallback_location: root_path
	end

	def destroy
	end

	private

  def authenticate_user
    unless current_user
      redirect_to new_session_path, danger: "Hmmmm, seems like you are not logged in 🤔"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dynamic_pages_helper.rb
module DynamicPagesHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def current_user
    User.find_by(id: session[:user_id])
  	end

   def log_in(user)
    session[:user_id] = user.id
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/cities/show.html.erb
	<div class="row justify-content-center align-items-center">
		<div class="col-md-12 col-sm-12">

		    <div class="jumbotron p-1 p-md-2 rounded bg-light" style="margin-bottom: 2vh">
			  <div class="container">
			    <h3 class="display-4 playfair"><%= @city.name %></h3>
			    <p class="lead"><%= @city.zip_code %></p>
			    <hr>
			    <p>Here are all the gossips from the city <%= @city.name %></p>
			  </div>
			</div>

		 </div>
	</div>

	<% @gossips.each do |gossip| %>

		<div class="card" style="margin-bottom: 2vh">
		<div class="card-body">
			<h4 class="card-title font-weight-bold playfair-relative"> <%= gossip.title.capitalize %> <span class="badge badge-info badgecustom"><%= Comment.where(gossip: gossip.id).count %></span></h4>
			<div class="row">
				<div class="col">
					<p class="card-text"> <%= User.find(gossip.user_id).first_name %></p>
				</div>

				<div class="col text-right">
					<%= link_to "Read more about the gossip ##{gossip.id}", gossip_path(gossip.id), :class => "btn btn-outline-dark" %>
				</div>
			</div>
		</div>
	</div>

	<% end %>

app/views/comments/edit.html.erb
     <div class="row justify-content-center align-items-center my-row">

            <div class="col-md-8 col-sm-12">

                  <%= form_tag url_for(action: 'update'), method: "put" do %>

                    <div class="form-group">
                      <%= label_tag 'Content' %>
                      <%= text_area_tag 'content', "#{@comment.content}", :class => "form-control", :rows => "4" %>
                      <small id="emailHelp" class="form-text text-muted">Unlimited characters 🔥 👨‍💻 👩‍💻 🔥 !</small>
                    </div>

                    <%= submit_tag "Edit Comment", :class => "btn btn-dark btn-sm" %> 

                    <%= link_to "Delete", gossip_comment_path(params[:gossip_id], params[:id]), :class => "btn btn-danger btn-sm", :data => { :confirm => "Are you sure?" }, :method => "delete" %>

                  <% end %>

                  
            </div>

      </div>

app/views/gossips/edit.html.erb
     <div class="row justify-content-center align-items-center my-row">

            <div class="col-md-8 col-sm-12">

                  <%= form_tag url_for(action: 'update'), method: "put" do %>

                    <div class="form-group">
                      <%= label_tag 'Title' %>
                      <%= text_field_tag 'title', "#{@gossip.title}", :class => "form-control", :placeholder => "Your gossip title in here" %>
                      <small id="emailHelp" class="form-text text-muted">Should be between 3 and 14 characters.</small>
                    </div>

                    <div class="form-group">
                      <%= label_tag 'Content' %>
                      <%= text_area_tag 'content', "#{@gossip.content}", :class => "form-control", :placeholder => "Your gossip in here", :rows => "4" %>
                      <small id="emailHelp" class="form-text text-muted">Unlimited characters 🔥 👨‍💻 👩‍💻 🔥 !</small>
                    </div>

                    <%= submit_tag "Edit Gossip", :class => "btn btn-dark" %>

                  <% end %>

            </div>

      </div>

app/views/gossips/index.html.erb
<%= link_to "Create a new gossip!", new_gossip_path, :class => "btn btn-dark btn-lg btn-block", :role => "button", :style => "margin-bottom: 5vh" %>

<% @gossips.each do |gossip| %>

	<div class="card" style="margin-bottom: 2vh">
		<div class="card-body">
			<h4 class="card-title font-weight-bold playfair-relative"> <%= gossip.title.capitalize %></h4>
			<div class="row">
				<div class="col">
					<p class="card-text"> <%= User.find(gossip.user_id).first_name %></p>
					
					<span class="badge badge-info">
						<%= Comment.where(gossip: gossip.id).count %> <span style="font-size: .8em">💬</span>
					</span> 

					<a href="<%= gossip_likes_path(gossip.id)%>" class="badge badge-light" data-method="post">
						<%= Like.where(gossip: gossip.id).count %> <span style="font-size: .8em">❤️</span>
					</a>
				</div>

				<div class="col text-right">
					<%= link_to "Read more about the gossip ##{gossip.id}", gossip_path(gossip.id), :class => "btn btn-outline-dark" %>
				</div>
			</div>
		</div>
	</div>

<% end %>

app/views/gossips/new.html.erb
      <div class="row justify-content-center align-items-center my-row">

            <div class="col-md-8 col-sm-12">

                  <%= form_tag url_for(action: 'create'), method: "post" do %>

                    <div class="form-group">
                      <%= label_tag 'Title' %>
                      <%= text_field_tag 'title', "", :class => "form-control", :placeholder => "Your gossip title in here" %>
                      <small id="emailHelp" class="form-text text-muted">Should be between 3 and 14 characters.</small>
                    </div>

                    <div class="form-group">
                      <%= label_tag 'Content' %>
                      <%= text_area_tag 'content', "", :class => "form-control", :placeholder => "Your gossip in here", :rows => "4" %>
                      <small id="emailHelp" class="form-text text-muted">Unlimited characters 🔥 👨‍💻 👩‍💻 🔥 !</small>
                    </div>

                    <%= submit_tag "Create Gossip", :class => "btn btn-dark" %>

                  <% end %>

            </div>

      </div>

app/views/gossips/show.html.erb
	<div class="row justify-content-center align-items-center my-row-2">
		<div class="col-md-8 col-sm-10">

			<div class="card" style="margin-bottom: 2vh">
		        <div class="card-body">
		            <h3 class="card-title font-weight-bold playfair"><%= @gossip.title.capitalize %></h3>

		            <div class="row">
		            <div class="col">
		            	<%= link_to "Author: #{User.find(@gossip.user_id).first_name}", author_path(@gossip.user_id), :class => "btn btn-dark" %>
		            </div>

		            <div class="col text-right">
		            	
		            		<%= link_to "City: #{User.find(@gossip.user_id).city.name}", city_path(@gossip.user.city_id), :class => "btn btn-outline-dark" %>
		        	</div>
		        	</div>

		            <hr>
		            <p class="card-text"><%= @gossip.content %></p>

		            <% if current_user == @gossip.user %>

 					<hr>

 					<div class="row">
			            <div class="col text-right">
			            	<%= link_to "Edit", edit_gossip_path(params[:id]), :class => "btn btn-info btn-sm" %>
			            	<%= link_to "Delete", gossip_path(params[:id]), :class => "btn btn-danger btn-sm", :data => { :confirm => "Are you sure?" }, :method => "delete" %>
			        	</div>
		        	</div>
		        	<% end %>
		        </div>
		    </div>
		 </div>
	</div>

	<div class="row justify-content-center align-items-center my-row-3">
		<div class="col-md-8 col-sm-10">
			
		    <ul class="list-group">
		    	
		    	<% @comments.each do |comment| %>
				  	<li class="list-group-item"> <b>

				  	<%= link_to "#{User.find(comment.user_id).first_name}", author_path(comment.user_id), :class =>"text-dark" %></b> : &nbsp;<em><%=comment.content%></em> 

				  	<% if current_user == comment.user %>

				  		<p class="text-right"><%= link_to "Edit", edit_gossip_comment_path(params[:id], comment.id), :class => "btn btn-info btn-sm" %></p>

				  	<% end %>

					</li>
				 <% end %>

				 	<li class="list-unstyled">
				 		
				 		<%= form_tag gossip_comments_path(params[:id]), :method => :post do %>

		                    <div class="form-group">
		                   	  <br/>
		                      <%= text_area_tag 'content', "", :class => "form-control", :placeholder => "Add your comment here !", :rows => "2" %>
		                      <small id="emailHelp" class="form-text text-muted">Unlimited characters 🔥 👨‍💻 👩‍💻 🔥 !</small>
		                    </div>

		                    <%= submit_tag "Create Comment", :class => "btn btn-dark btn-sm" %>

		                  <% end %>

				 	</li>

			</ul>
		 </div>
	</div>