config/routes.rb
Rails.application.routes.draw do
	root 'gossips#index'
  resources :gossips do
  	resources :comments
    resources :likes, only:[:create, :destroy]
  end
  resources :authors
  resources :cities
  resources :sessions, only:[:new,:create,:destroy]

  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'
  get '/welcome/:first_name', to: 'dynamic_pages#welcome', as: 'welcome'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	validates :name, presence: true
	validates :zip_code, 
		presence: true,
		uniqueness: true,
		format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "please enter a valid french zip code" }

	has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
	validates :content, presence: true

	belongs_to :gossip
	belongs_to :user
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	validates :title, 
		presence: true,
		length: {minimum: 3, maximum: 14}
	validates :content, presence: true
	
	belongs_to :user
	has_many :tag_gossip_joins
	has_many :tags, through: :tag_gossip_joins
	has_many :comments
	has_many :likes
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	validates :content, presence: true

	belongs_to :sender, class_name: "User"
	belongs_to :recipient, class_name: "User"	
end

app/models/tag.rb
class Tag < ApplicationRecord
	validates :title, 
		presence: true, 
		uniqueness: true

	has_many :tag_gossip_joins
	has_many :gossips, through: :tag_gossip_joins
end

app/models/tag_gossip_join.rb
class TagGossipJoin < ApplicationRecord
	belongs_to :tag 
	belongs_to :gossip 
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :email,
		presence: true,
		uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
    validates :city, presence: true
    validates :password, length: { minimum: 6 }, on: :create

	belongs_to :city
	has_many :gossips
	has_many :sent_messages, foreign_key: "sender_id", class_name: "PrivateMessage"
	has_many :received_messages, foreign_key: "recipient_id", class_name: "PrivateMessage"
	has_many :comments
	has_many :likes
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
  	@city = City.find(params[:id])
  	@users = User.where(city: params[:id])
  	@gossips = Gossip.where(user: @users.ids)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

	before_action :authenticate_user, only: [:create, :destroy]

	def create
		Like.create(user: current_user, gossip: Gossip.find(params[:gossip_id]))
		redirect_back fallback_location: root_path
	end

	def destroy
	end

	private

  def authenticate_user
    unless current_user
      redirect_to new_session_path, danger: "Hmmmm, seems like you are not logged in 🤔"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dynamic_pages_helper.rb
module DynamicPagesHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def current_user
    User.find_by(id: session[:user_id])
  	end

   def log_in(user)
    session[:user_id] = user.id
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Playfair+Display" rel="stylesheet">

  </head>

  <body>

    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light" style="margin-bottom: 5vh">
      <%= link_to "The Gossip Project", root_path, :class => "navbar-brand font-weight-bold playfair" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <%=link_to "Team", team_path, :class => "nav-item nav-link" %>
          </li>
          <li class="nav-item">
            <%=link_to "Contact", contact_path, :class => "nav-item nav-link" %>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
          <li class="nav-item dropleft">
                
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                User 🙂
                </a>
                <% if current_user %>

                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%=link_to "Profile", author_path(current_user.id), :class => "dropdown-item" %>
                  <%=link_to "Log out", session_path(current_user.id), :class => "dropdown-item", :method => "delete" %>
                  </div>
                </div>
                
                <% else %>

                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%=link_to "Log in", new_session_path, :class => "dropdown-item" %>
                  <%=link_to "Sign up", new_author_path, :class => "dropdown-item" %>
                  </div>
                </div>

                <% end %>
              </li>
        </ul>
      </div>
    </nav>


    <div class="container">
        
    <% flash.each do |name, msg| %>
    <div class="row justify-content-center">
        <div class="col-md-8 col-sm-12">
        <div class="alert alert-<%= name %> alert-dismissible fade show" role="alert">
          <%= msg %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
    </div>
    </div>
    <% end %>

      <%= yield %>

    </div>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>